# Generated by Django 4.2.17 on 2025-11-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Direction',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                        ('slug', models.SlugField(verbose_name='slug')),
                        ('accountable', models.CharField(blank=True, max_length=200, verbose_name='responsável')),
                        ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                    ],
                    options={
                        'verbose_name': 'diretoria',
                        'verbose_name_plural': 'diretorias',
                        'db_table': 'dashboard_direction',
                        'ordering': ('name',),
                    },
                ),
                migrations.CreateModel(
                    name='Sector',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                        ('slug', models.SlugField(verbose_name='slug')),
                        ('accountable', models.CharField(blank=True, max_length=200, verbose_name='responsável')),
                        ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                        ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefone')),
                        ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email')),
                        ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretorias', to='organizational_structure.direction', verbose_name='diretoria')),
                    ],
                    options={
                        'verbose_name': 'setor',
                        'verbose_name_plural': 'setores',
                        'db_table': 'dashboard_sector',
                        'ordering': ('name',),
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
