# Generated by Django 5.2.6 on 2025-12-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores', to='organizational_structure.direction', verbose_name='diretoria'),
        ),
    ]
