# Generated by Django 4.2.17 on 2025-11-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding_supplier', '0002_alter_contact_value_alter_supplier_cnpj_and_more'),
# <<<<<<< dev
        # Dashboard 0006 creates the tables (Bidding, Material) that we reference
        ('dashboard', '0006_bidding_material'),
# =======
        # Dashboard migrations must run first to create the shared tables (dashboard_bidding, etc)
#         ('dashboard', '0023_delete_material_delete_materialbidding'),
# >>>>>>> main
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Bidding',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                        ('slug', models.SlugField(verbose_name='slug')),
                        ('date', models.DateField(blank=True, null=True, verbose_name='data')),
                        ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', help_text='Status da licitação (propagado para materiais vinculados)', max_length=1, verbose_name='status')),
                    ],
                    options={
                        'verbose_name': 'licitação',
                        'verbose_name_plural': 'licitações',
                        'db_table': 'dashboard_bidding',
                        'ordering': ('date', 'name'),
                    },
                ),
                migrations.CreateModel(
                    name='Material',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                        ('slug', models.SlugField(verbose_name='slug')),
                    ],
                    options={
                        'verbose_name': 'material',
                        'verbose_name_plural': 'materiais',
                        'db_table': 'dashboard_material',
                        'ordering': ('name',),
                    },
                ),
                migrations.CreateModel(
                    name='MaterialBidding',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', help_text='Status deste material nesta licitação específica', max_length=1, verbose_name='status')),
                        ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço do material nesta licitação', max_digits=8, null=True, verbose_name='preço')),
                        ('readjustment', models.FloatField(default=0, help_text='Percentual de reajuste aplicado', verbose_name='reajuste (%)')),
                        ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot do preço do material quando foi adicionado à licitação', max_digits=8, null=True, verbose_name='preço no momento da inclusão')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='incluído em')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                        ('bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_associations', to='bidding_procurement.bidding', verbose_name='licitação')),
                        ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_associations', to='bidding_procurement.material', verbose_name='material')),
                        ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidding_materials', to='bidding_supplier.supplier', verbose_name='fornecedor')),
                    ],
                    options={
                        'verbose_name': 'material da licitação',
                        'verbose_name_plural': 'materiais das licitações',
                        'db_table': 'dashboard_materialbidding',
                        'ordering': ('bidding', 'material'),
                        'unique_together': {('material', 'bidding')},
                    },
                ),
                migrations.AddField(
                    model_name='material',
                    name='biddings',
                    field=models.ManyToManyField(blank=True, related_name='materials', through='bidding_procurement.MaterialBidding', to='bidding_procurement.bidding', verbose_name='licitações'),
                ),
            ],
            database_operations=[],
        ),
    ]
