# Generated by Django 5.2.6 on 2025-11-28 14:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0001_initial'),
        ('bidding_supplier', '0002_alter_contact_value_alter_supplier_cnpj_and_more'),
        # Dashboard 0008 creates MaterialBidding table which this migration alters
        ('dashboard', '0008_add_materialbidding_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='administrative_process',
            field=models.CharField(blank=True, help_text='Ex: 121/25', max_length=20, verbose_name='processo administrativo'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='modality',
            field=models.CharField(blank=True, help_text='Ex: PREGÃO ELETRÔNICO', max_length=100, verbose_name='modalidade'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='modality_number',
            field=models.IntegerField(blank=True, help_text='Ex: 38', null=True, verbose_name='número da modalidade'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='object_description',
            field=models.TextField(blank=True, verbose_name='objeto/descrição'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='prazo de validade'),
        ),
        migrations.AlterField(
            model_name='materialbidding',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Preço do material nesta licitação', max_digits=10, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='materialbidding',
            name='readjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de reajuste aplicado', max_digits=10, verbose_name='reajuste'),
        ),
        migrations.AlterField(
            model_name='materialbidding',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', help_text='Status do material nesta licitação específica', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='materialbidding',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Fornecedor que venceu este item na licitação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_biddings', to='bidding_supplier.supplier', verbose_name='fornecedor vencedor'),
        ),
    ]
