# Generated by Django 5.2.6 on 2025-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0002_bidding_administrative_process_bidding_modality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbidding',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Quantidade total licitada deste material', verbose_name='quantidade licitada'),
        ),
    ]
