# Generated by Django 5.2.6 on 2025-12-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0003_materialbidding_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, help_text='Marca do material (ex: TSA AD-09, DEKO 764-J CAT6)', max_length=200, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, help_text='Unidade de medida (ex: un, M, pc, cx)', max_length=20, verbose_name='unidade'),
        ),
    ]
