# Generated by Django 5.2.6 on 2025-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0004_material_brand_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbidding',
            name='quantity_delivered',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade entregue aos setores', verbose_name='quantidade entregue'),
        ),
        migrations.AddField(
            model_name='materialbidding',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade recebida via notas fiscais', verbose_name='quantidade recebida'),
        ),
    ]
