# Generated by Django 5.2.6 on 2025-12-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0005_materialbidding_quantity_delivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialbidding',
            name='quantity_delivered',
        ),
        migrations.RemoveField(
            model_name='materialbidding',
            name='quantity_received',
        ),
        migrations.AddField(
            model_name='materialbidding',
            name='quantity_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade já comprada via notas fiscais (não pode ultrapassar o limite licitado)', verbose_name='quantidade comprada'),
        ),
    ]
