# Generated by Django 5.2.6 on 2025-12-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0006_adjust_purchase_limit_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialbidding',
            name='price_snapshot',
        ),
    ]
