# Generated by Django 5.2.6 on 2025-12-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0007_remove_materialbidding_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbidding',
            name='brand',
            field=models.CharField(
                blank=True,
                help_text='Marca do material nesta licitação (ex: TSA AD-09, DEKO 764-J)',
                max_length=200,
                verbose_name='marca',
            ),
        ),
    ]
