# Generated by Django 5.2.6 on 2025-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identificador único do procedimento (ex: consolidate_duplicates_v1)', max_length=100, unique=True, verbose_name='nome do procedimento')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='executado em')),
                ('success', models.BooleanField(default=True, help_text='Se o procedimento foi executado com sucesso', verbose_name='sucesso')),
                ('notes', models.TextField(blank=True, help_text='Informações adicionais sobre a execução', verbose_name='notas')),
            ],
            options={
                'verbose_name': 'procedimento de deploy',
                'verbose_name_plural': 'procedimentos de deploy',
                'ordering': ['-executed_at'],
            },
        ),
    ]
