# Generated by Django 4.2.5 on 2023-10-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_courseold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
    ]
