# Generated by Django 4.2.7 on 2023-11-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="nome"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "accountable",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="responsavel"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DI", "Diretoria"),
                            ("SE", "Secretária"),
                            ("DE", "Departamento"),
                            ("GA", "Gabinete"),
                        ],
                        max_length=2,
                        verbose_name="tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "diretoria",
                "verbose_name_plural": "diretorias",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="nome"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "accountable",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="responsavel"
                    ),
                ),
                ("phone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.direction",
                    ),
                ),
            ],
            options={
                "verbose_name": "setor",
                "verbose_name_plural": "setores",
                "ordering": ["direction", "name"],
            },
        ),
    ]
