# Generated by Django 4.2.7 on 2023-11-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_sector_email_alter_sector_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('status', models.CharField(blank=True, choices=[('1', 'Ativo'), ('2', 'Inativo')], default=1, max_length=1, verbose_name='status')),
                ('date', models.DateField(blank=True, null=True, verbose_name='data')),
            ],
            options={
                'verbose_name': 'licitação',
                'verbose_name_plural': 'licitações',
                'ordering': ('status', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('status', models.CharField(blank=True, choices=[('1', 'Ativo'), ('2', 'Inativo')], default=1, max_length=1, verbose_name='status')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor')),
                ('readjustment', models.FloatField(default=0, verbose_name='reajuste')),
                ('bidding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='dashboard.bidding', verbose_name='licitação')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ('status', 'bidding', 'name'),
            },
        ),
    ]
