# Generated by Django 4.2.7 on 2023-11-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_supplier', '0001_initial'),
        ('dashboard', '0006_bidding_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores', to='bidding_supplier.supplier', verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='bidding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitações', to='dashboard.bidding', verbose_name='licitação'),
        ),
    ]
