# Generated by Django 4.2.17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Fase 1: Criar tabela MaterialBidding SEM remover campos de Material.
    
    Isso permite migrar dados de forma segura antes de deletar campos antigos.
    """
    
    dependencies = [
        ('dashboard', '0007_material_supplier_alter_material_bidding'),
    ]

    operations = [
        # Criar modelo MaterialBidding
        migrations.CreateModel(
            name='MaterialBidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('1', 'Ativo'), ('2', 'Inativo')],
                    default='1',
                    help_text='Status deste material nesta licitação específica',
                    max_length=1,
                    verbose_name='status'
                )),
                ('price_snapshot', models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    help_text='Snapshot do preço do material quando foi adicionado à licitação',
                    max_digits=8,
                    null=True,
                    verbose_name='preço no momento da inclusão'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='incluído em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bidding', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='material_associations',
                    to='dashboard.bidding',
                    verbose_name='licitação'
                )),
                ('material', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='bidding_associations',
                    to='dashboard.material',
                    verbose_name='material'
                )),
            ],
            options={
                'verbose_name': 'material da licitação',
                'verbose_name_plural': 'materiais das licitações',
                'ordering': ('bidding', 'material'),
                'unique_together': {('material', 'bidding')},
            },
        ),
    ]
