# Generated by Django 5.2.6 on 2025-11-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_supplier', '0002_alter_contact_value_alter_supplier_cnpj_and_more'),
        ('dashboard', '0007_material_supplier_alter_material_bidding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidding',
            options={'ordering': ('date', 'name'), 'verbose_name': 'licitação', 'verbose_name_plural': 'licitações'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name', 'supplier'), 'verbose_name': 'material', 'verbose_name_plural': 'materiais'},
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='status',
        ),
        migrations.RemoveField(
            model_name='material',
            name='bidding',
        ),
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço base do material (sem reajuste)', max_digits=8, null=True, verbose_name='valor base'),
        ),
        migrations.AlterField(
            model_name='material',
            name='readjustment',
            field=models.FloatField(default=0, help_text='Percentual de reajuste aplicado sobre o preço base', verbose_name='reajuste padrão (%)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='bidding_supplier.supplier', verbose_name='fornecedor'),
        ),
        migrations.CreateModel(
            name='MaterialBidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', help_text='Status deste material nesta licitação específica', max_length=1, verbose_name='status')),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot do preço do material quando foi adicionado à licitação', max_digits=8, null=True, verbose_name='preço no momento da inclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='incluído em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_associations', to='dashboard.bidding', verbose_name='licitação')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_associations', to='dashboard.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'material da licitação',
                'verbose_name_plural': 'materiais das licitações',
                'ordering': ('bidding', 'material'),
                'unique_together': {('material', 'bidding')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='biddings',
            field=models.ManyToManyField(blank=True, related_name='materials', through='dashboard.MaterialBidding', to='dashboard.bidding', verbose_name='licitações'),
        ),
    ]
