# Generated by Django 4.2.17

from django.db import migrations


def consolidate_duplicates(apps, schema_editor):
    """
    Consolida materiais duplicados mantendo apenas o mais antigo (menor ID).
    
    Critério de duplicata: mesmo nome + mesmo fornecedor
    
    Para cada grupo de duplicatas:
    1. Identifica o material a manter (primeiro criado = menor ID)
    2. Atualiza referências para apontar para o material mantido
    3. Remove duplicatas
    """
    Material = apps.get_model('dashboard', 'Material')
    
    try:
        MaterialReport = apps.get_model('reports', 'MaterialReport')
        has_reports = True
    except LookupError:
        has_reports = False
    
    from django.db.models import Count
    
    # Encontrar duplicatas (nome + fornecedor iguais)
    duplicates = Material.objects.values(
        'name', 'supplier_id'
    ).annotate(
        total=Count('id')
    ).filter(total__gt=1)
    
    total_removed = 0
    total_updated_reports = 0
    
    print("\n" + "="*80)
    print("CONSOLIDANDO MATERIAIS DUPLICADOS")
    print("="*80 + "\n")
    
    for dup_group in duplicates:
        # Buscar todos os materiais deste grupo
        materials = Material.objects.filter(
            name=dup_group['name'],
            supplier_id=dup_group['supplier_id']
        ).order_by('id')  # Ordem por ID (mais antigo primeiro)
        
        if materials.count() <= 1:
            continue
        
        # Material a manter (primeiro/mais antigo)
        keeper = materials.first()
        # Duplicatas a remover
        duplicates_to_remove = materials.exclude(id=keeper.id)
        
        supplier_name = keeper.supplier.trade if keeper.supplier else "Sem fornecedor"
        print(f"Material: '{keeper.name}' ({supplier_name})")
        print(f"  Mantendo ID={keeper.id}")
        print(f"  Removendo IDs: {[m.id for m in duplicates_to_remove]}")
        
        # Atualizar referências de MaterialReport (se houver)
        if has_reports:
            for duplicate in duplicates_to_remove:
                updated_count = MaterialReport.objects.filter(
                    material=duplicate
                ).update(material=keeper)
                
                if updated_count > 0:
                    print(f"    ↳ {updated_count} MaterialReport(s) atualizados")
                    total_updated_reports += updated_count
        
        # Remover duplicatas
        removed_count = duplicates_to_remove.count()
        duplicates_to_remove.delete()
        total_removed += removed_count
        print()
    
    print("="*80)
    print(f"RESUMO DA CONSOLIDAÇÃO:")
    print(f"  Materiais removidos: {total_removed}")
    if has_reports:
        print(f"  MaterialReports atualizados: {total_updated_reports}")
    print("="*80 + "\n")


def reverse_consolidation(apps, schema_editor):
    """
    Não há como reverter consolidação de forma automática.
    Restaure do backup se necessário.
    """
    print("⚠️  AVISO: Consolidação não é reversível automaticamente.")
    print("   Use o backup do banco de dados para reverter.")


class Migration(migrations.Migration):
    """
    Fase 2: Consolidar materiais duplicados.
    
    Mantém apenas o material mais antigo (menor ID) de cada grupo duplicado.
    """
    
    dependencies = [
        ('dashboard', '0008_add_materialbidding_table'),
    ]

    operations = [
        migrations.RunPython(
            consolidate_duplicates,
            reverse_consolidation
        ),
    ]
