# Generated by Django 4.2.17

from django.db import migrations
from decimal import Decimal


def migrate_materials_to_materialbidding(apps, schema_editor):
    """
    Migra dados de Material.bidding + Material.status para MaterialBidding.
    
    Para cada Material que tem bidding:
    - Cria MaterialBidding com material, bidding, status
    - Captura preço como snapshot
    """
    Material = apps.get_model('dashboard', 'Material')
    MaterialBidding = apps.get_model('dashboard', 'MaterialBidding')
    
    # Buscar materiais que TÊM licitação
    materials_with_bidding = Material.objects.exclude(bidding__isnull=True)
    
    created_count = 0
    skipped_count = 0
    
    print("\n" + "="*80)
    print("MIGRANDO DADOS PARA MATERIALBIDDING")
    print("="*80 + "\n")
    
    for material in materials_with_bidding:
        # Verificar se já existe (evitar duplicatas em re-runs)
        if MaterialBidding.objects.filter(
            material=material,
            bidding=material.bidding
        ).exists():
            skipped_count += 1
            continue
        
        # Calcular preço total (base + reajuste)
        price = material.price if material.price else Decimal('0.00')
        if material.readjustment and material.readjustment != 0:
            price_float = float(price) + (float(price) * (material.readjustment / 100))
            price = Decimal(str(price_float)).quantize(Decimal('0.00'))
        
        # Pegar status se existir
        status = '1'  # Default
        if hasattr(material, 'status') and material.status:
            status = str(material.status)
        
        # Criar MaterialBidding
        MaterialBidding.objects.create(
            material=material,
            bidding=material.bidding,
            status=status,
            price_snapshot=price
        )
        
        created_count += 1
        
        if created_count % 50 == 0:
            print(f"  Migrados {created_count} materiais...")
    
    print("\n" + "="*80)
    print(f"RESUMO DA MIGRAÇÃO:")
    print(f"  MaterialBidding criados: {created_count}")
    print(f"  Já existentes (pulados): {skipped_count}")
    print(f"  Total em MaterialBidding: {MaterialBidding.objects.count()}")
    print("="*80 + "\n")


def reverse_migration(apps, schema_editor):
    """Remover todos os MaterialBidding criados"""
    MaterialBidding = apps.get_model('dashboard', 'MaterialBidding')
    count = MaterialBidding.objects.count()
    MaterialBidding.objects.all().delete()
    print(f"✓ Revertido: {count} MaterialBidding removidos")


class Migration(migrations.Migration):
    """
    Fase 3: Migrar dados de Material para MaterialBidding.
    
    Preserva todos os vínculos Material→Bidding na nova tabela intermediária.
    """
    
    dependencies = [
        ('dashboard', '0009_consolidate_duplicate_materials'),
    ]

    operations = [
        migrations.RunPython(
            migrate_materials_to_materialbidding,
            reverse_migration
        ),
    ]
