# Generated by Django 4.2.17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Fase 4: Adicionar ManyToManyField e atualizar Meta dos modelos.
    
    Prepara os modelos para o estado final antes de remover campos antigos.
    """
    
    dependencies = [
        ('dashboard', '0010_migrate_to_materialbidding'),
    ]

    operations = [
        # Adicionar ManyToManyField em Material
        migrations.AddField(
            model_name='material',
            name='biddings',
            field=models.ManyToManyField(
                blank=True,
                related_name='materials',
                through='dashboard.MaterialBidding',
                to='dashboard.bidding',
                verbose_name='licitações'
            ),
        ),
        
        # Atualizar Meta do Material (remover status e bidding do ordering)
        migrations.AlterModelOptions(
            name='material',
            options={
                'ordering': ('name', 'supplier'),
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais'
            },
        ),
        
        # Atualizar Meta do Bidding (remover status do ordering)
        migrations.AlterModelOptions(
            name='bidding',
            options={
                'ordering': ('date', 'name'),
                'verbose_name': 'licitação',
                'verbose_name_plural': 'licitações'
            },
        ),
        
        # Atualizar campos de Material com novos help_text
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Preço base do material (sem reajuste)',
                max_digits=8,
                null=True,
                verbose_name='valor base'
            ),
        ),
        migrations.AlterField(
            model_name='material',
            name='readjustment',
            field=models.FloatField(
                default=0,
                help_text='Percentual de reajuste aplicado sobre o preço base',
                verbose_name='reajuste padrão (%)'
            ),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='materials',
                to='bidding_supplier.supplier',
                verbose_name='fornecedor'
            ),
        ),
    ]
