# Generated by Django 4.2.17

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fase 5 FINAL: Remove campos antigos que não são mais necessários.
    
    ATENÇÃO: Esta é a migration DESTRUTIVA. Backup é necessário
    se precisar reverter além deste ponto.
    """
    
    dependencies = [
        ('dashboard', '0011_add_manytomany_cleanup_model'),
    ]

    operations = [
        # Remover campo status de Material
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        
        # Remover campo bidding de Material (FK antiga)
        migrations.RemoveField(
            model_name='material',
            name='bidding',
        ),
        
        # Remover campo status de Bidding
        migrations.RemoveField(
            model_name='bidding',
            name='status',
        ),
    ]
