# Generated by Django 4.2.17 on 2025-11-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_old_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ('name',), 'verbose_name': 'diretoria', 'verbose_name_plural': 'diretorias'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('name',), 'verbose_name': 'setor', 'verbose_name_plural': 'setores'},
        ),
        migrations.RemoveField(
            model_name='direction',
            name='kind',
        ),
        migrations.AddField(
            model_name='direction',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='accountable',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(default='', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='accountable',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diretorias', to='dashboard.direction', verbose_name='diretoria'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(default='', verbose_name='slug'),
        ),
    ]
