# Generated by Django 4.2.17 on 2025-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_direction_options_alter_sector_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='accountable',
            field=models.CharField(blank=True, max_length=200, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='accountable',
            field=models.CharField(blank=True, max_length=200, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
