# Generated by Django 4.2.17 on 2025-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20251124_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', help_text='Status da licitação (propagado para materiais vinculados)', max_length=1, verbose_name='status'),
        ),
    ]
