# Generated by Django 4.2.17 on 2025-11-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_sector'),
        ('dashboard', '0020_remove_fields_from_material'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='sector',
                    name='direction',
                ),
                migrations.DeleteModel(
                    name='Direction',
                ),
                migrations.DeleteModel(
                    name='Sector',
                ),
            ],
            database_operations=[],
        ),
    ]
