# Generated by Django 4.2.17 on 2025-11-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_sector_direction_delete_direction_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='material',
                    name='biddings',
                ),
                migrations.AlterUniqueTogether(
                    name='materialbidding',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='materialbidding',
                    name='bidding',
                ),
                migrations.RemoveField(
                    model_name='materialbidding',
                    name='material',
                ),
                migrations.RemoveField(
                    model_name='materialbidding',
                    name='supplier',
                ),
                migrations.DeleteModel(
                    name='Bidding',
                ),
            ],
            database_operations=[],
        ),
    ]
