# Generated by Django 4.2.17 on 2025-11-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_materialreport_material'),
        ('dashboard', '0022_remove_material_biddings_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Material',
                ),
                migrations.DeleteModel(
                    name='MaterialBidding',
                ),
            ],
            database_operations=[],
        ),
    ]
