# Generated by Django 5.2.6 on 2025-12-22 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0023_delete_material_delete_materialbidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status')),
                ('result', models.TextField(blank=True, verbose_name='resultado')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
            ],
            options={
                'verbose_name': 'job de backup',
                'verbose_name_plural': 'jobs de backup',
                'ordering': ['-created_at'],
            },
        ),
    ]
