# Generated by Django 5.2.6 on 2025-12-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_supplier', '0002_alter_contact_value_alter_supplier_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='bidding_supplier.supplier', verbose_name='fornecedor'),
        ),
    ]
