# Generated by Django 5.2.6 on 2025-12-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_supplier', '0003_alter_contact_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['trade', 'company'], 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
    ]
