# Generated by Django 4.2.7 on 2023-12-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0007_material_supplier_alter_material_bidding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bidding_supplier", "0002_alter_contact_value_alter_supplier_cnpj_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_report",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="identificação do laudo",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "employee",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="funcionario"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Aguardando ..."), ("2", "Finalizado")],
                        default=1,
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                ("justification", models.TextField(verbose_name="justificativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "pro_accountable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsável",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profissional responsável",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profissional",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profissional",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.sector",
                        verbose_name="setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "laudo",
                "verbose_name_plural": "laudos",
            },
        ),
        migrations.CreateModel(
            name="MaterialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="quantidade"
                    ),
                ),
                (
                    "unitary_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="valor",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiais",
                        to="dashboard.material",
                        verbose_name="material",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laudos",
                        to="reports.report",
                        verbose_name="laudo",
                    ),
                ),
            ],
            options={
                "verbose_name": "materiais do laudo",
                "verbose_name_plural": "materiais do laudo",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_number",
                    models.CharField(max_length=10, verbose_name="numero da Nota"),
                ),
                (
                    "access_key",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="chave de acesso",
                    ),
                ),
                (
                    "note_issuance_date",
                    models.DateField(verbose_name="data da emissão da nota"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fornecedor",
                        to="bidding_supplier.supplier",
                        verbose_name="fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota fiscal",
                "verbose_name_plural": "notas fiscais",
                "ordering": ("note_issuance_date", "supplier", "note_number"),
            },
        ),
        migrations.CreateModel(
            name="InterestRequestMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=20, verbose_name="valor")),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[("S", "Solicitação"), ("E", "Empenho")],
                        max_length=1,
                        null=True,
                        verbose_name="kind",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.invoice",
                        verbose_name="nota fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitação ou empenho",
                "verbose_name_plural": "solicitações ou empenhos",
            },
        ),
    ]
