# Generated by Django 4.2.7 on 2023-12-05 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0002_interestrequestmaterial_report_alter_report_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["created_at", "status", "updated_at"],
                "verbose_name": "laudo",
                "verbose_name_plural": "laudos",
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="pro_accountable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="responsável",
                to=settings.AUTH_USER_MODEL,
                verbose_name="profissional responsável",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profissional",
                to=settings.AUTH_USER_MODEL,
                verbose_name="profissional",
            ),
        ),
    ]
