# Generated by Django 4.2.17 on 2025-11-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_structure', '0001_initial'),
        ('reports', '0004_alter_report_options_alter_materialreport_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizational_structure.sector', verbose_name='setor'),
        ),
    ]
