# Generated by Django 4.2.17 on 2025-11-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0001_initial'),
        ('reports', '0005_alter_report_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialreport',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='bidding_procurement.material', verbose_name='material'),
        ),
    ]
