# Generated by Django 5.2.6 on 2025-12-01 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0003_materialbidding_quantity'),
        ('reports', '0007_safe_add_material_bidding'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='materialreport',
                    name='material',
                ),
                migrations.AddField(
                    model_name='invoice',
                    name='file',
                    field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='arquivo da nota'),
                ),
                migrations.AddField(
                    model_name='invoice',
                    name='xml_content',
                    field=models.TextField(blank=True, null=True, verbose_name='conteúdo XML'),
                ),
                migrations.AddField(
                    model_name='materialreport',
                    name='material_bidding',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_laudos', to='bidding_procurement.materialbidding', verbose_name='material da licitação'),
                ),
            ],
            database_operations=[],
        )
    ]
