# Generated by Django 5.2.6 on 2025-12-16 19:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0005_materialbidding_quantity_delivered_and_more'),
        ('bidding_supplier', '0003_alter_contact_supplier'),
        ('organizational_structure', '0002_alter_sector_direction'),
        ('reports', '0008_remove_materialreport_material_invoice_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestrequestmaterial',
            options={'verbose_name': 'solicitação ou empenho (legado)', 'verbose_name_plural': 'solicitações ou empenhos (legado)'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'nota fiscal', 'verbose_name_plural': 'notas fiscais'},
        ),
        migrations.AlterModelOptions(
            name='materialreport',
            options={'verbose_name': 'material do laudo', 'verbose_name_plural': 'materiais do laudo'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivered_to_purchases',
            field=models.BooleanField(default=False, verbose_name='entregue ao compras'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivered_to_purchases_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='entregue ao compras em'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=datetime.date(2025, 12, 16), verbose_name='data de emissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(default=0, max_length=20, verbose_name='número da nota'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'supplier')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='observations',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='foto da nota'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('R', 'Recebida'), ('E', 'Entregue')], default='P', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='materialreport',
            name='quantity_delivered',
            field=models.PositiveIntegerField(default=0, verbose_name='qtd entregue'),
        ),
        migrations.AddField(
            model_name='report',
            name='delivered_items',
            field=models.PositiveIntegerField(default=0, verbose_name='itens entregues'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_items',
            field=models.PositiveIntegerField(default=0, verbose_name='total de itens'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='access_key',
            field=models.CharField(blank=True, help_text='44 dígitos da chave de acesso da NFe', max_length=44, verbose_name='chave de acesso'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='bidding_supplier.supplier', verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='materialreport',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='materialreport',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='reports.report', verbose_name='laudo'),
        ),
        migrations.AlterField(
            model_name='materialreport',
            name='unitary_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pro_accountable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laudos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='profissional responsável'),
        ),
        migrations.AlterField(
            model_name='report',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laudos_criados', to=settings.AUTH_USER_MODEL, verbose_name='profissional'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('1', 'Aberto'), ('2', 'Aguardando'), ('3', 'Finalizado')], default='1', max_length=1, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='número do empenho')),
                ('commitment_date', models.DateField(verbose_name='data do empenho')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='reports.invoice', verbose_name='nota fiscal')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='reports.report', verbose_name='laudo')),
            ],
            options={
                'verbose_name': 'empenho',
                'verbose_name_plural': 'empenhos',
                'ordering': ['-commitment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_by', models.CharField(max_length=200, verbose_name='recebido por')),
                ('received_at', models.DateTimeField(verbose_name='data/hora do recebimento')),
                ('observations', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='reports.commitment', verbose_name='empenho')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='entregue por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='reports.invoice', verbose_name='nota fiscal')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizational_structure.sector', verbose_name='setor destinatário')),
            ],
            options={
                'verbose_name': 'ficha de entrega',
                'verbose_name_plural': 'fichas de entrega',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.invoice', verbose_name='nota fiscal')),
                ('material_bidding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_notas', to='bidding_procurement.materialbidding', verbose_name='material')),
            ],
            options={
                'verbose_name': 'item da nota fiscal',
                'verbose_name_plural': 'itens da nota fiscal',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.PositiveIntegerField(verbose_name='quantidade entregue')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.deliverynote', verbose_name='ficha de entrega')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='reports.invoiceitem', verbose_name='item da nota')),
            ],
            options={
                'verbose_name': 'item da entrega',
                'verbose_name_plural': 'itens da entrega',
            },
        ),
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255, blank=True, null=True, verbose_name='arquivo')),
                ('file_type', models.CharField(choices=[('L', 'Laudo Escaneado'), ('O', 'Outro')], default='L', max_length=1, verbose_name='tipo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reports.report', verbose_name='laudo')),
            ],
            options={
                'verbose_name': 'documento do laudo',
                'verbose_name_plural': 'documentos do laudo',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='note_issuance_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='xml_content',
        ),
    ]
