# Generated by Django 5.2.6 on 2025-12-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_interestrequestmaterial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreport',
            name='quantity_delivered',
        ),
        migrations.RemoveField(
            model_name='report',
            name='delivered_items',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_items',
        ),
    ]
