# Generated by Django 5.2.6 on 2025-12-17 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
        ('reports', '0010_adjust_purchase_limit_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='invoice_item',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='interestrequestmaterial',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscal.invoice', verbose_name='nota fiscal'),
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='material_bidding',
        ),
        migrations.DeleteModel(
            name='Commitment',
        ),
        migrations.DeleteModel(
            name='DeliveryNote',
        ),
        migrations.DeleteModel(
            name='DeliveryNoteItem',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
