# Generated by Django 5.2.6 on 2025-12-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_migrate_waiting_status_to_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('1', 'Aberto'), ('3', 'Finalizado')], default='1', max_length=1, verbose_name='status'),
        ),
    ]
