# Generated by Django 5.2.6 on 2025-12-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_refactor_commitment_and_add_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdocument',
            name='file',
            field=models.CharField(blank=True, help_text='Path do arquivo no Supabase Storage ou URL', max_length=255, null=True, verbose_name='arquivo'),
        ),
    ]
