# Generated by Django 5.2.6 on 2025-12-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_cloudinary_from_reportdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestRequestMaterial',
        ),
    ]
