# Generated by Django 5.2.6 on 2025-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_delete_interest_request_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='closing_reason',
            field=models.TextField(blank=True, help_text='Motivo preenchido manualmente ao finalizar o laudo sem nota fiscal', null=True, verbose_name='motivo do fechamento'),
        ),
    ]
