# Generated by Django 5.2.6 on 2025-12-17 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding_procurement', '0006_adjust_purchase_limit_control'),
        ('bidding_supplier', '0003_alter_contact_supplier'),
        ('organizational_structure', '0002_alter_sector_direction'),
        ('reports', '0010_adjust_purchase_limit_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='número do empenho')),
                ('commitment_date', models.DateField(verbose_name='data do empenho')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='reports.report', verbose_name='laudo')),
            ],
            options={
                'verbose_name': 'empenho',
                'verbose_name_plural': 'empenhos',
                'ordering': ['-commitment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='número da nota')),
                ('issue_date', models.DateField(verbose_name='data de emissão')),
                ('access_key', models.CharField(blank=True, help_text='44 dígitos da chave de acesso da NFe', max_length=44, verbose_name='chave de acesso')),
                ('photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='foto da nota')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Recebida'), ('E', 'Entregue')], default='P', max_length=1, verbose_name='status')),
                ('delivered_to_purchases', models.BooleanField(default=False, verbose_name='entregue ao compras')),
                ('delivered_to_purchases_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue ao compras em')),
                ('observations', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='bidding_supplier.supplier', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
                'ordering': ['-issue_date', '-created_at'],
                'unique_together': {('number', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_by', models.CharField(max_length=200, verbose_name='recebido por')),
                ('received_at', models.DateTimeField(verbose_name='data/hora do recebimento')),
                ('observations', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='fiscal.commitment', verbose_name='empenho')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='entregue por')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizational_structure.sector', verbose_name='setor destinatário')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='fiscal.invoice', verbose_name='nota fiscal')),
            ],
            options={
                'verbose_name': 'ficha de entrega',
                'verbose_name_plural': 'fichas de entrega',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commitment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='fiscal.invoice', verbose_name='nota fiscal'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fiscal.invoice', verbose_name='nota fiscal')),
                ('material_bidding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_notas', to='bidding_procurement.materialbidding', verbose_name='material')),
            ],
            options={
                'verbose_name': 'item da nota fiscal',
                'verbose_name_plural': 'itens da nota fiscal',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.PositiveIntegerField(verbose_name='quantidade entregue')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fiscal.deliverynote', verbose_name='ficha de entrega')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='fiscal.invoiceitem', verbose_name='item da nota')),
            ],
            options={
                'verbose_name': 'item da entrega',
                'verbose_name_plural': 'itens da entrega',
            },
        ),
    ]
