# Generated by Django 5.2.6 on 2025-12-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_procurement', '0006_adjust_purchase_limit_control'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='saldo em estoque')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('material_bidding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='bidding_procurement.materialbidding', verbose_name='material licitado')),
            ],
            options={
                'verbose_name': 'item em estoque',
                'verbose_name_plural': 'estoque',
            },
        ),
    ]
