# Generated by Django 5.2.6 on 2025-12-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_stockitem'),
        ('reports', '0013_refactor_commitment_and_add_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitment',
            options={'ordering': ['-created_at'], 'verbose_name': 'empenho', 'verbose_name_plural': 'empenhos'},
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='report',
        ),
        migrations.AddField(
            model_name='commitment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='reports.report', verbose_name='laudo vinculado'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='commitment_date',
            field=models.DateField(blank=True, null=True, verbose_name='data do empenho'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commitment', to='fiscal.invoice', verbose_name='nota fiscal'),
        ),
    ]
