# Generated by Django 5.2.6 on 2025-12-18 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_refactor_commitment_and_add_report'),
        ('reports', '0013_refactor_commitment_and_add_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='commitment_date',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='report',
        ),
        migrations.CreateModel(
            name='InvoiceReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='vinculado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_link', to='fiscal.invoice', verbose_name='nota fiscal')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_report_links', to=settings.AUTH_USER_MODEL, verbose_name='vinculado por')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='reports.report', verbose_name='laudo')),
            ],
            options={
                'verbose_name': 'vínculo nota-laudo',
                'verbose_name_plural': 'vínculos nota-laudo',
                'ordering': ['-linked_at'],
            },
        ),
    ]
