# Generated by Django 5.2.6 on 2025-12-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_simplify_commitment_add_invoice_report_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='commitment',
        ),
        migrations.AddField(
            model_name='invoice',
            name='commitment_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='número do empenho'),
        ),
    ]
