# Generated by Django 5.2.6 on 2025-12-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_remove_deliverynote_commitment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commitment',
        ),
    ]
