# Generated by Django 5.2.6 on 2025-12-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_delete_commitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='número do empenho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commitment', to='fiscal.invoice', verbose_name='nota fiscal')),
            ],
            options={
                'verbose_name': 'empenho',
                'verbose_name_plural': 'empenhos',
                'ordering': ['-created_at'],
            },
        ),
    ]
