# Generated by Django 5.2.6 on 2025-12-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_commitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='commitment_number',
        ),
    ]
