# Generated by Django 5.2.6 on 2025-12-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_remove_invoice_commitment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_index', models.IntegerField(unique=True, verbose_name='índice da chave')),
                ('exhausted_at', models.DateTimeField(blank=True, null=True, verbose_name='esgotada em')),
            ],
            options={
                'verbose_name': 'status de chave API',
                'verbose_name_plural': 'status de chaves API',
            },
        ),
    ]
