# Generated by Django 5.2.6 on 2025-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_add_ocrjob_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='hash da imagem'),
        ),
    ]
