# Generated by Django 5.2.6 on 2025-12-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0011_add_image_hash_to_ocrjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='photo',
            field=models.CharField(blank=True, help_text='Path da imagem (Supabase: UUID.jpg ou Cloudinary: public_id)', max_length=255, null=True, verbose_name='foto da nota'),
        ),
    ]
