# Generated by Django 5.2.6 on 2025-12-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0012_change_photo_to_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ['-created_at'], 'verbose_name': 'ficha de entrega', 'verbose_name_plural': 'fichas de entrega'},
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='signed_document',
            field=models.CharField(blank=True, help_text='Path da imagem no Supabase (delivery-documents/)', max_length=255, verbose_name='documento assinado'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída')], default='P', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data/hora do recebimento'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='recebido por'),
        ),
    ]
