# Generated by Django 5.2.6 on 2025-12-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0013_add_delivery_status_and_signed_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Endereço/localização de referência para a entrega', max_length=300, verbose_name='endereço de entrega'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'A Caminho'), ('C', 'Concluída')], default='P', max_length=1, verbose_name='status'),
        ),
    ]
