# Generated by Django 5.2.6 on 2025-12-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0014_add_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteitem',
            name='stock_updated',
            field=models.BooleanField(default=False, help_text='Indica se o estoque físico já foi baixado para este item', verbose_name='estoque atualizado'),
        ),
    ]
