# Generated by Django 5.2.6 on 2025-12-30 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_supplier', '0004_add_supplier_ordering'),
        ('fiscal', '0015_deliverynoteitem_stock_updated'),
        ('organizational_structure', '0002_alter_sector_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['status'], name='fiscal_deli_status_5e77a2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='fiscal_invo_status_ebae99_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='fiscal_invo_issue_d_b8ccd0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='fiscal_invo_status_9f3f26_idx'),
        ),
    ]
