# Generated by Django 4.2.7 on 2023-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, verbose_name='primeiro nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='ultimo nome')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='usuario')),
                ('registration', models.CharField(max_length=8, verbose_name='numero de matrícula')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles_pic', verbose_name='foto perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_tech', models.BooleanField(default=False, verbose_name='tecnico')),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrador')),
                ('first_login', models.BooleanField(default=True, verbose_name='primeiro login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
                'ordering': ['is_admin', 'is_tech', 'first_name'],
            },
        ),
    ]
