# Generated by Django 4.2.7 on 2023-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionaluser",
            name="registration",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="numero de matrícula"
            ),
        ),
    ]
