# Generated by Django 4.2.7 on 2023-11-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0002_alter_professionaluser_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionaluser",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/profiles_pic",
                verbose_name="foto perfil",
            ),
        ),
    ]
