# Generated by Django 4.2.7 on 2023-11-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_professionaluser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaluser',
            name='profile_pic',
        ),
    ]
