# Generated by Django 5.2.6 on 2025-12-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_remove_professionaluser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaluser',
            name='username',
        ),
    ]
